---
azs:
- name: us-west-2a
  cloud_properties:
    availability_zone: us-west-2a
networks:
- name: boshnet
  type: manual
  subnets:
  - dns:
    - 10.0.0.2
    range: 10.0.0.0/24
    gateway: 10.0.0.1
    azs:
    - us-west-2a
    cloud_properties:
      subnet: subnet-ff595298
    reserved:
    - 10.0.0.2-10.0.0.10
    - 10.0.0.62-10.0.0.254
    static:
    - 10.0.0.15
    - 10.0.0.16
    - 10.0.0.17
    - 10.0.0.18
vm_types:
- name: t2.micro
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk:
      type: gp2
      size: 8192
      encrypted: false
    raw_instance_storage: false
- name: t2.small
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      type: gp2
      size: 8192
      encrypted: false
    raw_instance_storage: false
- name: t2.medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      type: gp2
      size: 32768
      encrypted: false
    raw_instance_storage: false
- name: c4.large
  cloud_properties:
    instance_type: c4.large
    ephemeral_disk:
      type: gp2
      size: 32768
      encrypted: false
    raw_instance_storage: false
- name: m4.large
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk:
      type: gp2
      size: 32768
      encrypted: false
    raw_instance_storage: false
- name: r4.large
  cloud_properties:
    instance_type: r4.large
    ephemeral_disk:
      type: gp2
      size: 65536
      encrypted: false
    raw_instance_storage: false
- name: c4.xlarge
  cloud_properties:
    instance_type: c4.xlarge
    ephemeral_disk:
      type: gp2
      size: 65536
      encrypted: false
    raw_instance_storage: false
- name: m4.xlarge
  cloud_properties:
    instance_type: m4.xlarge
    ephemeral_disk:
      type: gp2
      size: 65536
      encrypted: false
    raw_instance_storage: false
- name: r4.xlarge
  cloud_properties:
    instance_type: r4.xlarge
    ephemeral_disk:
      type: gp2
      size: 131072
      encrypted: false
    raw_instance_storage: false
- name: c4.2xlarge
  cloud_properties:
    instance_type: c4.2xlarge
    ephemeral_disk:
      type: gp2
      size: 131072
      encrypted: false
    raw_instance_storage: false
- name: m4.2xlarge
  cloud_properties:
    instance_type: m4.2xlarge
    ephemeral_disk:
      type: gp2
      size: 131072
      encrypted: false
    raw_instance_storage: false
- name: r4.2xlarge
  cloud_properties:
    instance_type: r4.2xlarge
    ephemeral_disk:
      type: gp2
      size: 262144
      encrypted: false
    raw_instance_storage: false
- name: c4.4xlarge
  cloud_properties:
    instance_type: c4.4xlarge
    ephemeral_disk:
      type: gp2
      size: 262144
      encrypted: false
    raw_instance_storage: false
- name: r4.4xlarge
  cloud_properties:
    instance_type: r4.4xlarge
    ephemeral_disk:
      type: gp2
      size: 524288
      encrypted: false
    raw_instance_storage: false
- name: i2.8xlarge
  cloud_properties:
    instance_type: i2.8xlarge
    ephemeral_disk:
      type: gp2
      size: 983040
      encrypted: false
    raw_instance_storage: true
- name: d2.8xlarge
  cloud_properties:
    instance_type: d2.8xlarge
    ephemeral_disk:
      type: gp2
      size: 983040
      encrypted: false
    raw_instance_storage: true
disk_types:
- name: '1024'
  disk_size: 1024
  cloud_properties:
    type: gp2
    encrypted: false
- name: '2048'
  disk_size: 2048
  cloud_properties:
    type: gp2
    encrypted: false
- name: '5120'
  disk_size: 5120
  cloud_properties:
    type: gp2
    encrypted: false
- name: '10240'
  disk_size: 10240
  cloud_properties:
    type: gp2
    encrypted: false
- name: '20480'
  disk_size: 20480
  cloud_properties:
    type: gp2
    encrypted: false
- name: '30720'
  disk_size: 30720
  cloud_properties:
    type: gp2
    encrypted: false
- name: '51200'
  disk_size: 51200
  cloud_properties:
    type: gp2
    encrypted: false
- name: '76800'
  disk_size: 76800
  cloud_properties:
    type: gp2
    encrypted: false
- name: '102400'
  disk_size: 102400
  cloud_properties:
    type: gp2
    encrypted: false
- name: '153600'
  disk_size: 153600
  cloud_properties:
    type: gp2
    encrypted: false
- name: '204800'
  disk_size: 204800
  cloud_properties:
    type: gp2
    encrypted: false
- name: '307200'
  disk_size: 307200
  cloud_properties:
    type: gp2
    encrypted: false
- name: '512000'
  disk_size: 512000
  cloud_properties:
    type: gp2
    encrypted: false
- name: '768000'
  disk_size: 768000
  cloud_properties:
    type: gp2
    encrypted: false
- name: '1048576'
  disk_size: 1048576
  cloud_properties:
    type: gp2
    encrypted: false
- name: '2097152'
  disk_size: 2097152
  cloud_properties:
    type: gp2
    encrypted: false
- name: '5242880'
  disk_size: 5242880
  cloud_properties:
    type: gp2
    encrypted: false
- name: '10485760'
  disk_size: 10485760
  cloud_properties:
    type: gp2
    encrypted: false
- name: '16777216'
  disk_size: 16777216
  cloud_properties:
    type: gp2
    encrypted: false
compilation:
  workers: 5
  network: boshnet
  az: us-west-2a
  reuse_compilation_vms: true
  vm_type: c4.xlarge
  vm_extensions: []
vm_extensions:
- name: public_ip
  cloud_properties:
    auto_assign_public_ip: true
- name: vm-extension-concourse-worker
  cloud_properties:
    elbs:
    - concourse-elb
    ephemeral_disk:
      size: 32768
