= Ops Lab 1: CF Task Scheduler - Deploy New BOSH
This repositiory is a lab showing the functionality of CF tasks.  Its intended audience is for an Ops team or anyone with a CF deployment wanting to efficiently deploy multiple BOSH environments.  

Note the architecture of this application is a simple link:https://pypi.python.org/pypi/python-cfworker[Python-CFWorker] server running in CF, with a Shell script used as the task.

Disclaimer: This repo is not a substitute for a properly designed tool, however could be utilized as a starting point.

== Requirements
* PCF or CF running on AWS
* Subnet in the PCF VPC not currently being used for PCF Runtime (e.g. pcf_public_subnet2)

== Prepare AWS Account
* If necessary, follow instructions from BOSH.IO: link:https://bosh.io/docs/init-aws.html#prepare-aws[(Step1 - Prepare AWS Account)]
* Double check you have a *bosh security group* as outlined above

== Deploy to Cloud Foundry
. Update the Manifest with some default parameters including your RSA private key
+
----
$ cat manifest.yml

applications:
- name: bosh-create
  memory: 128M
  buildpack: python_buildpack
  env:
    director_name: bosh1
    internal_cidr: 10.0.0.0/24
    internal_gw: 10.0.0.1
    internal_ip: 10.0.0.6
    access_key_id: ZXCKI76698SD4OA
    secret_access_key: Eoivxsdsdlb+59FZfHOiM
    region: us-west-2
    az: us-west-2a
    default_key_name: boshprivatekey
    default_security_group: bosh
    subnet_id: subnet-ff12348
    private_key_value: "-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
MIIEogIBAAKCAQEAsBhgMTdQwAtQNSCJ+9IUs10vqvBuceYVHDDXD/hXMDRiNujauR1eSH1sjpYZ
3cHqzUynS5a437DjHJjq1HN4hcSwSeSUYOilUnTzhrZMfbXNQmw7IxEXabxPSFU/iCo=
-----END RSA PRIVATE KEY-----"

----
. CF Push the Bosh-Create application
+
----
$ cf push -f manifest.yml
----

== Schedule a CF Task
Schedule the creation of a BOSH env by running the CF Run-Task command while overiding the default parameters for *director_name* and *internal_ip*. You may do this by passing the values as arguments to the *create_env.sh* script. See the script to understand how this is performed.
----
$ cf run-task bosh-create /home/vcap/app/create_env.sh bosh2 10.0.0.6
----

== View Running and Completed Tasks
. See the logs of a current task
+
----
$ cf logs bosh-create

...
...
2017-07-06T12:48:28.382-07:00 [APP/TASK/create-env/0] [ERR] 2017-07-06 19:48:28 (4.22 MB/s) - 'bosh2' saved [19598478/19598478]
2017-07-06T12:48:33.383-07:00 [APP/TASK/create-env/0] [OUT] Setting proper permissions on Bosh CLI
2017-07-06T12:48:33.385-07:00 [APP/TASK/create-env/0] [ERR] Cloning into 'bosh-deployment'...
2017-07-06T12:48:33.874-07:00 [APP/TASK/create-env/0] [OUT] Done cloning bosh-deployment
2017-07-06T12:48:34.943-07:00 [APP/PROC/WEB/0] [OUT] Task server is running
2017-07-06T12:48:38.875-07:00 [APP/TASK/create-env/0] [OUT] Creating new BOSH Environment
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT Done deploying new BOSH!
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT admin_password: p5r345tgVF1260vr
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT blobstore_agent_password: wdqgFkz6v5Jd4f4VX
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT blobstore_director_password: e0x1dx7890jr
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT hm_password: g1l1dj73ix1fp
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT mbus_bootstrap_password: qs3fqz50wpi6t
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT nats_password: uw0d37dhrn1l6jv
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT postgres_password: k138fnrh5pdFGR3di
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT registry_password: 9ikh545FGt8H7umv
2017-07-06T12:56:29.90-0700 [APP/TASK/create-env/0]OUT Exit status 0
2017-07-06T12:56:29.92-0700 [APP/TASK/create-env/0]OUT Destroying container
2017-07-06T12:56:30.38-0700 [APP/TASK/create-env/0]OUT Successfully destroyed container

----

. See the status of tasks
+
----
$ cf tasks bosh-create

Getting tasks for app bosh-create in org Team Awesome / space development as bbertka...
OK

id   name         state       start time                      command
1    create-env   SUCCEEDED   Thu, 06 Jul 2017 19:48:21 UTC   /home/vcap/app/create_env.sh bosh2 10.0.0.6
----

== Using your new BOSH
. Target your BOSH (within VPC)
+
----
ubuntu@ip-10-0-0-70:~$ bosh target 10.0.0.6
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Target set to 'bosh2'
----
+
----
ubuntu@ip-10-0-0-70:~$ bosh login
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Your username: admin
Enter password:
Logged in as 'admin'
----
+
----
ubuntu@ip-10-0-0-70:~$ bosh status
Config
             /home/ubuntu/.bosh_config

Director
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
  Name       bosh2
  URL        https://10.0.0.6:25555
  Version    262.3.0 (00000000)
  User       admin
  UUID       a904c750-4868-4f85-a1bb-7182842402f3
  CPI        aws_cpi
  dns        disabled
  compiled_package_cache disabled
  snapshots  disabled
  config_server disabled

Deployment
  not set
----

. Connect to your BOSH instance via SSH (within VPC)
+
----
$ ssh -i pcf.pem vcap@10.0.0.6
----

== Congratulations you are now a PCF Task Master!

Check out the official docs for more info: link:https://docs.pivotal.io/pivotalcf/1-11/devguide/using-tasks.html[Using Tasks on PCF]

Note, versions of PCF 1.11 allow CF Task control via Apps Manager GUI -- check it out!


== Next Lab - link:https://github.com/bbertka-pivotal/bosh-concourse-lab[Deploy Concourse!]
