---
name: concourse
director_uuid: 42793282-07fd-4431-984c-a80df4e2a18e

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: c4.large
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # this instance group to your ELB
  - vm-extension-concourse-worker
  stemcell: trusty
  azs: [us-west-2a]
  networks: [{name: boshnet}]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: https://concourse.pcfninja.com

      # replace with username/password, or configure GitHub auth
      basic_auth_username: concourse
      basic_auth_password: changeme

      # replace with your SSL cert and key
      tls_cert: | 
        -----BEGIN CERTIFICATE-----
        MIIDEjCCAfoCCQDFYXvpOvGahjANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJV
        UzELMAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxHTAbBgNVBAsTFFBpdm90
        YWwgU29mdHdhcmUgSW5jMB4XDTE3MDcxMDE3MzEwMFoXDTE4MDcxMDE3MzEwMFow
        SzELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMR0w
        GwYDVQQLExRQaXZvdGFsIFNvZnR3YXJlIEluYzCCASIwDQYJKoZIhvcNAQEBBQAD
        ggEPADCCAQoCggEBAKitv0TLY0nbAsE1CweH+EKEKsk5hplohkDgKrPlWdsnbUXm
        jvHF34g4nwL88yNuw7M09xw8HR/lgZbzCqkKWJCeWBBpmk3dnsE/9m8WHMJ1vg7b
        1MZHBNl0axx7eRIAmhPZ/SLy12UVoDYg2LRzy/2mhvOE7BiJvbv68UJ4CtKxz1+g
        JDIIL/vHaOwdZpkcJvK4HN9zkJ6W98Jg9TaaL54TT0oA7Ot/txdFSf7R0QTMxEQ/
        87OjCttGvu7igHpbi24XB9n1X9jZcPLCNka6ooXMU8z6H5EPiEMLbs1LIFnOXBsw
        TKW9cvnb4ymZWMKlpSpiJnOskwIukMypnC7OHC8CAwEAATANBgkqhkiG9w0BAQsF
        AAOCAQEAk5JGon3sbI2SFSV+cGYn6PDO85eQiolkwq33c0xQ9dx0BRUAvJo5/XyX
        YN/IC3CZMxD+d1vytI/IffRZy7FKvRH9i9U3xax2x8asVeH8UulF6A79FN1LvzS4
        JP9lKR5HVgXqL1tYEo0MQaEW1FtlD/2RVDjXoWc+AQJh7nj47iGa8H4wIaoWJxmv
        varVUK2H/quu1V9HkWMhb3lRIxY8/7vTUSIcAG4u74U04hxSZl81h3OTOOTmnjC5
        wVnQF5DQAfvcsD3Srw5d2c2ItQ+RFNgkHFkXHRFsQ+WE1ec9WBds6g5tgoykek7d
        hV177u5GJuCwBfmkT3fCYgMHLP2Nkg==
        -----END CERTIFICATE-----

      tls_key: | 
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAqK2/RMtjSdsCwTULB4f4QoQqyTmGmWiGQOAqs+VZ2ydtReaO
        8cXfiDifAvzzI27DszT3HDwdH+WBlvMKqQpYkJ5YEGmaTd2ewT/2bxYcwnW+DtvU
        xkcE2XRrHHt5EgCaE9n9IvLXZRWgNiDYtHPL/aaG84TsGIm9u/rxQngK0rHPX6Ak
        Mggv+8do7B1mmRwm8rgc33OQnpb3wmD1NpovnhNPSgDs63+3F0VJ/tHRBMzERD/z
        s6MK20a+7uKAeluLbhcH2fVf2Nlw8sI2RrqihcxTzPofkQ+IQwtuzUsgWc5cGzBM
        pb1y+dvjKZlYwqWlKmImc6yTAi6QzKmcLs4cLwIDAQABAoIBAEfdjsoupWTIDMpo
        YQSaZ6lfSiNlgPVHVTu6xjbTFo+KosHPU0Oq/Gu7Q/Qv9R85h+OIQ2giLH50d9vq
        PLZ8k/M5o2eKtpVKQOMw7zuw/hvTsl/+RQ8dHvHO6fu+l3yWCQ9AJtuG/0IwDoxB
        PlLTqyuskX6bOUPTG6VFaxjYsDPHoPKRRG+KEZE0VmH7YXIcpOG7vHbur1at5TxJ
        0zItdPqP9/LQ2ZKPSuZfENMEMOjeT01K7v49FXhBlfdaIpoPHmhUEj0bsArHEs8m
        3mk/KPXE37Ttm4GhREdRx03e3/F83k7eapGk/j/Shy5JKHS7AJ0fWAky6r9+s2Y+
        DKWRBmECgYEAz95/xOAVlRzi9EnC3kvnsFUOwsSUSosinWU7TA7PCMyEVhh/7r2m
        fgnm2Vj4Q0ydmraV5s0BcYYcFx6S3FMfxXGoEqhXfKikMuMGpc4qjQ6E374nI7TN
        Pvdu2ImTNutGSjq9bNdm6tCpEWGaIMkennRDt0yi6FK1Ji9QkzbVkwkCgYEAz7w5
        Vn4ifZM8VE2x4DZ8HUs7YmfI07cZXdieC+raujD0xk00FbXq/wTz37s9UyRcMigv
        r7PbH8i72B9g4NPzSKQLsg1PgWTXuoLfUzmZI+zWfDOFuhfiEvCRpwvAu8nEmfmQ
        QUP4+oBwF4I0OTj+/dXS1txFGMaaHwDd288Ca3cCgYEAp82c5ShkI9iK2dvFpMAv
        y6gOX2pjr318NwUmhjKaLSc0WXAzrl2Izsxdf+2TlHh/7gohHo018hfqCzvSIGw2
        BKTIoi8lWOumibG9hxHURcSHvTr6y5dD7OW/pKwCnF33gyrCCeAlI7/IC9D3pCnX
        PuDqXUlPZS6HL8kYSY8FgEkCgYBZkT1jppT2ceJEMw+rrbJL6yEap8b2Se79AKX8
        W3Gdb/hJ/AWmCr7c3+TKpW+mhnneAme1KSYkiSc84yKhLaGqw1hrl8Oc9b7yIvVp
        a980lyxPduOEvkFyixkx3iZmkXNcNDdXfJhAYdpyuGgN+B4xkd0LWQPNz+upzHTc
        DmBrtwKBgGzvQ0tUh6KgfwFeJbo/hLecz/KwQSHSLPhUZISCpxMiKq5uANwsZiNh
        LWgSZne3hTCK9rtBDV/4AzNsxPOd1VeCDSu0AJrQsAqV0uGCc+3yqq/9BH5gtgpO
        /KI2IuRDx/aZbtICnEp0Xv7DVu6OFQfd/j4bs2L9+iBmx9EoZ2Xu
        -----END RSA PRIVATE KEY-----

      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: c4.large
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: 51200
  azs: [us-west-2a]
  networks: [{name: boshnet}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: concourse
        password: changeme

- name: worker
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: c4.large
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # sufficient ephemeral storage to VMs in this instance group.
  - vm-extension-concourse-worker
  stemcell: trusty
  azs: [us-west-2a]
  networks: [{name: boshnet}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
